### PR TITLE
EASYOPAC-1224 - Import translations on module update.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
https://inlead.atlassian.net/browse/EASYOPAC-1224

Update translations.

### CODE REVIEW

**Review by guddo — CHANGES_REQUESTED** [review]
Changes seems OK, however I don't see all the fields in the translation files.

**Comment by NicolaeGrigoriu** [comment]
@guddo what field you mean?
https://github.com/easySuite/bibdk_subject_hierarchy/blob/EASYOPAC-1224/translations/bibdk_subject_hierarchy.da.po

**Comment by guddo** [comment]
@NicolaeGrigoriu 
image

**Comment by guddo** [comment]
LGTM but general.po does not seem to be updated? @NicolaeGrigoriu

**Review by guddo — APPROVED** [review]

**Review by guddo — APPROVED** [review]

**Pull request merged**
